/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from SmacoDevs.MyShared.Enums.DataType */
export enum DataType {
    PositiveNegative = 1,
    Numeric = 2,
    Text = 3,
    Percentage = 4,
    MultiSelect = 5,
    Date = 6,
}

/** Transpiled from SmacoDevs.MyShared.Enums.MedicalNoteDataType */
export enum MedicalNoteDataType {
    Text = 3,
    MultiSelect = 5,
    Date = 6,
}

/** Transpiled from SmacoDevs.MyShared.Enums.Status */
export enum Status {
    Inactive = 0,
    Active = 1,
    Deleted = 2,
    Testing = 3,
}

